#!/usr/bin/env python3
"""
audio2header.py - Convert any audio file to a C header for PROGMEM playback on VS1053.

Requires: ffmpeg (must be in PATH)

Usage:
  python tools/audio2header.py beep.wav                          -> sounds/beep.h
  python tools/audio2header.py announce.mp3 -o sounds/custom.h   -> sounds/custom.h
  python tools/audio2header.py ding.wav --name snd_ding          -> sounds/ding.h (array: snd_ding)
  python tools/audio2header.py voice.wav --bitrate 48k           -> higher quality
"""

import subprocess
import sys
import os
import argparse
import tempfile


def main():
    parser = argparse.ArgumentParser(
        description="Convert audio to C header (mono MP3) for PROGMEM"
    )
    parser.add_argument("input", help="Input audio file (any format ffmpeg supports)")
    parser.add_argument("-o", "--output", help="Output .h file (default: sounds/<stem>.h)")
    parser.add_argument("--name", help="C array name (default: derived from output filename)")
    parser.add_argument("--bitrate", default="32k", help="MP3 bitrate (default: 32k)")
    parser.add_argument(
        "--samplerate", type=int, default=22050, help="Sample rate Hz (default: 22050)"
    )
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        sys.exit(f"Error: {args.input} not found")

    stem = os.path.splitext(os.path.basename(args.input))[0]

    if not args.output:
        sounds_dir = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "sounds"
        )
        os.makedirs(sounds_dir, exist_ok=True)
        args.output = os.path.join(sounds_dir, f"{stem}.h")

    if not args.name:
        args.name = os.path.splitext(os.path.basename(args.output))[0]

    # sanitize to valid C identifier
    cname = "".join(c if c.isalnum() or c == "_" else "_" for c in args.name)
    if cname[0].isdigit():
        cname = "_" + cname

    # convert to mono low-bitrate MP3 via ffmpeg
    with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as tmp:
        tmppath = tmp.name

    try:
        cmd = [
            "ffmpeg", "-y", "-i", args.input,
            "-ac", "1",
            "-ar", str(args.samplerate),
            "-b:a", args.bitrate,
            "-codec:a", "libmp3lame",
            tmppath,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            sys.exit(f"ffmpeg error:\n{result.stderr}")

        with open(tmppath, "rb") as f:
            data = f.read()
    finally:
        os.unlink(tmppath)

    # write C header
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as f:
        f.write(f"// Auto-generated by audio2header.py from {os.path.basename(args.input)}\n")
        f.write(f"// {len(data)} bytes, mono {args.bitrate} @ {args.samplerate} Hz\n")
        f.write("#pragma once\n\n")
        f.write(f"const unsigned char {cname}[] PROGMEM = {{\n")

        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
            comma = "," if i + 16 < len(data) else ""
            f.write(f"  {hex_str}{comma}\n")

        f.write("};\n")
        f.write(f"const unsigned int {cname}_len = {len(data)};\n")

    print(f"{args.output}: {cname}[{len(data)}] ({len(data) / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
